import { Language } from '../interfaces/language'

export const languages: Language[] = [
    { id: 1, text: 'APL', value: 'text/apl' },
    { id: 2, text: 'PGP', value: 'application/pgp' },
    { id: 3, text: 'ASN.1', value: '1' },
    { id: 4, text: 'Asterisk', value: 'text/x-asterisk' },
    { id: 5, text: 'Brainfuck', value: 'text/x-brainfuck' },
    { id: 6, text: 'C', value: 'text/x-csrc' },
    { id: 7, text: 'C++', value: 'text/x-c++src' },
    { id: 8, text: 'Cobol', value: 'text/x-cobol' },
    { id: 9, text: 'C#', value: 'text/x-csharp' },
    { id: 10, text: 'Clojure', value: 'text/x-clojure' },
    { id: 11, text: 'ClojureScript', value: 'text/x-clojurescript' },
    { id: 12, text: 'Closure Stylesheets (GSS)', value: 'text/x-gss' },
    { id: 13, text: 'CMake', value: 'text/x-cmake' },
    { id: 14, text: 'CoffeeScript', value: 'text/x-coffeescript' },
    { id: 15, text: 'Common Lisp', value: 'text/x-common-lisp' },
    { id: 16, text: 'Cypher', value: 'application/x-cypher-query' },
    { id: 17, text: 'Cython', value: 'text/x-cython' },
    { id: 18, text: 'Crystal', value: 'text/x-crystal' },
    { id: 19, text: 'CSS', value: 'text/css' },
    { id: 20, text: 'CQL', value: 'text/x-cassandra' },
    { id: 21, text: 'D', value: 'text/x-d' },
    { id: 22, text: 'Dart', value: 'application/dart' },
    { id: 23, text: 'diff', value: 'text/x-diff' },
    { id: 24, text: 'Django', value: 'text/x-django' },
    { id: 25, text: 'Dockerfile', value: 'text/x-dockerfile' },
    { id: 26, text: 'DTD', value: 'application/xml-dtd' },
    { id: 27, text: 'Dylan', value: 'text/x-dylan' },
    { id: 28, text: 'EBNF', value: 'text/x-ebnf' },
    { id: 29, text: 'ECL', value: 'text/x-ecl' },
    { id: 30, text: 'edn', value: 'application/edn' },
    { id: 31, text: 'Eiffel', value: 'text/x-eiffel' },
    { id: 32, text: 'Elm', value: 'text/x-elm' },
    { id: 33, text: 'Embedded Javascript', value: 'application/x-ejs' },
    { id: 34, text: 'Embedded Ruby', value: 'application/x-erb' },
    { id: 35, text: 'Erlang', value: 'text/x-erlang' },
    { id: 36, text: 'Factor', value: 'text/x-factor' },
    { id: 37, text: 'FCL', value: 'text/x-fcl' },
    { id: 38, text: 'Forth', value: 'text/x-forth' },
    { id: 39, text: 'Fortran', value: 'text/x-fortran' },
    { id: 40, text: 'F#', value: 'text/x-fsharp' },
    { id: 41, text: 'Gas', value: 'text/x-gas' },
    { id: 42, text: 'Gherkin', value: 'text/x-feature' },
    { id: 43, text: 'GitHub Flavored Markdown', value: 'text/x-gfm' },
    { id: 44, text: 'Go', value: 'text/x-go' },
    { id: 45, text: 'Groovy', value: 'text/x-groovy' },
    { id: 46, text: 'HAML', value: 'text/x-haml' },
    { id: 47, text: 'Haskell', value: 'text/x-haskell' },
    { id: 48, text: 'Haskell (Literate)', value: 'text/x-literate-haskell' },
    { id: 49, text: 'Haxe', value: 'text/x-haxe' },
    { id: 50, text: 'HXML', value: 'text/x-hxml' },
    { id: 51, text: 'ASP.NET', value: 'T' },
    { id: 52, text: 'HTML', value: 'text/html' },
    { id: 53, text: 'HTTP', value: 'message/http' },
    { id: 54, text: 'IDL', value: 'text/x-idl' },
    { id: 55, text: 'Pug', value: 'text/x-pug' },
    { id: 56, text: 'Java', value: 'text/x-java' },
    { id: 57, text: 'Java Server Pages', value: 'application/x-jsp' },
    { id: 58, text: 'JavaScript', value: 'text/javascript' },
    { id: 59, text: 'JSON', value: 'application/json' },
    { id: 60, text: 'JSON-LD', value: 'application/ld+json' },
    { id: 61, text: 'JSX', value: 'text/jsx' },
    { id: 62, text: 'Jinja2', value: 'null' },
    { id: 63, text: 'Julia', value: 'text/x-julia' },
    { id: 64, text: 'Kotlin', value: 'text/x-kotlin' },
    { id: 65, text: 'LESS', value: 'text/x-less' },
    { id: 66, text: 'LiveScript', value: 'text/x-livescript' },
    { id: 67, text: 'Lua', value: 'text/x-lua' },
    { id: 68, text: 'Markdown', value: 'text/x-markdown' },
    { id: 69, text: 'mIRC', value: 'text/mirc' },
    { id: 70, text: 'MariaDB SQL', value: 'text/x-mariadb' },
    { id: 71, text: 'Mathematica', value: 'text/x-mathematica' },
    { id: 72, text: 'Modelica', value: 'text/x-modelica' },
    { id: 73, text: 'MUMPS', value: 'text/x-mumps' },
    { id: 74, text: 'MS SQL', value: 'text/x-mssql' },
    { id: 75, text: 'mbox', value: 'application/mbox' },
    { id: 76, text: 'MySQL', value: 'text/x-mysql' },
    { id: 77, text: 'Nginx', value: 'text/x-nginx-conf' },
    { id: 78, text: 'NSIS', value: 'text/x-nsis' },
    { id: 79, text: 'NTriples', value: 'text/n-triples' },
    { id: 80, text: 'Objective C', value: 'text/x-objectivec' },
    { id: 81, text: 'OCaml', value: 'text/x-ocaml' },
    { id: 82, text: 'Octave', value: 'text/x-octave' },
    { id: 83, text: 'Oz', value: 'text/x-oz' },
    { id: 84, text: 'Pascal', value: 'text/x-pascal' },
    { id: 85, text: 'PEG.js', value: 's' },
    { id: 86, text: 'Perl', value: 'text/x-perl' },
    { id: 87, text: 'PHP', value: 'application/x-httpd-php' },
    { id: 88, text: 'Pig', value: 'text/x-pig' },
    { id: 89, text: 'Plain Text', value: 'text/plain' },
    { id: 90, text: 'PLSQL', value: 'text/x-plsql' },
    { id: 91, text: 'PowerShell', value: 'application/x-powershell' },
    { id: 92, text: 'Properties files', value: 'text/x-properties' },
    { id: 93, text: 'ProtoBuf', value: 'text/x-protobuf' },
    { id: 94, text: 'Python', value: 'text/x-python' },
    { id: 95, text: 'Puppet', value: 'text/x-puppet' },
    { id: 96, text: 'Q', value: 'text/x-q' },
    { id: 97, text: 'R', value: 'text/x-rsrc' },
    { id: 98, text: 'reStructuredText', value: 'text/x-rst' },
    { id: 99, text: 'RPM Changes', value: 'text/x-rpm-changes' },
    { id: 100, text: 'RPM Spec', value: 'text/x-rpm-spec' },
    { id: 101, text: 'Ruby', value: 'text/x-ruby' },
    { id: 102, text: 'Rust', value: 'text/x-rustsrc' },
    { id: 103, text: 'SAS', value: 'text/x-sas' },
    { id: 104, text: 'Sass', value: 'text/x-sass' },
    { id: 105, text: 'Scala', value: 'text/x-scala' },
    { id: 106, text: 'Scheme', value: 'text/x-scheme' },
    { id: 107, text: 'SCSS', value: 'text/x-scss' },
    { id: 108, text: 'Shell', value: 'text/x-sh' },
    { id: 109, text: 'Sieve', value: 'application/sieve' },
    { id: 110, text: 'Slim', value: 'text/x-slim' },
    { id: 111, text: 'Smalltalk', value: 'text/x-stsrc' },
    { id: 112, text: 'Smarty', value: 'text/x-smarty' },
    { id: 113, text: 'Solr', value: 'text/x-solr' },
    { id: 114, text: 'Soy', value: 'text/x-soy' },
    { id: 115, text: 'SPARQL', value: 'application/sparql-query' },
    { id: 116, text: 'Spreadsheet', value: 'text/x-spreadsheet' },
    { id: 117, text: 'SQL', value: 'text/x-sql' },
    { id: 118, text: 'SQLite', value: 'text/x-sqlite' },
    { id: 119, text: 'Squirrel', value: 'text/x-squirrel' },
    { id: 120, text: 'Stylus', value: 'text/x-styl' },
    { id: 121, text: 'Swift', value: 'text/x-swift' },
    { id: 122, text: 'sTeX', value: 'text/x-stex' },
    { id: 123, text: 'LaTeX', value: 'text/x-latex' },
    { id: 124, text: 'SystemVerilog', value: 'text/x-systemverilog' },
    { id: 125, text: 'Tcl', value: 'text/x-tcl' },
    { id: 126, text: 'Textile', value: 'text/x-textile' },
    { id: 127, text: 'TiddlyWiki ', value: 'text/x-tiddlywiki' },
    { id: 128, text: 'Tiki wiki', value: 'text/tiki' },
    { id: 129, text: 'TOML', value: 'text/x-toml' },
    { id: 130, text: 'Tornado', value: 'text/x-tornado' },
    { id: 131, text: 'troff', value: 'text/troff' },
    { id: 132, text: 'TTCN', value: 'text/x-ttcn' },
    { id: 133, text: 'TTCN_CFG', value: 'text/x-ttcn-cfg' },
    { id: 134, text: 'Turtle', value: 'text/turtle' },
    { id: 135, text: 'TypeScript', value: 'application/typescript' },
    { id: 136, text: 'TypeScript-JSX', value: 'text/typescript-jsx' },
    { id: 137, text: 'Twig', value: 'text/x-twig' },
    { id: 138, text: 'Web IDL', value: 'text/x-webidl' },
    { id: 139, text: 'VB.NET', value: 'T' },
    { id: 140, text: 'VBScript', value: 'text/vbscript' },
    { id: 141, text: 'Velocity', value: 'text/velocity' },
    { id: 142, text: 'Verilog', value: 'text/x-verilog' },
    { id: 143, text: 'VHDL', value: 'text/x-vhdl' },
    { id: 144, text: 'Vue.js Component', value: 'script/x-vue' },
    { id: 145, text: 'XML', value: 'application/xml' },
    { id: 146, text: 'XQuery', value: 'application/xquery' },
    { id: 147, text: 'Yacas', value: 'text/x-yacas' },
    { id: 148, text: 'YAML', value: 'text/x-yaml' },
    { id: 149, text: 'Z80', value: 'text/x-z80' },
    { id: 150, text: 'mscgen', value: 'text/x-mscgen' },
    { id: 151, text: 'xu', value: 'text/x-xu' },
    { id: 152, text: 'msgenny', value: 'text/x-msgenny' }
]
