language: node_js
sudo: false
node_js:
- node
- '6.0'
notifications:
  slack:
    secure: qduzjSQ17SEiiJiE+p7w75G2m6cVq9MS321s0h0CFsKX2+8W/0Og3HJ0+XFmleq2hqGzEAoIFsP8J79uL2jFYLK23DjlEI3pTNKQLogOLSo22TmMf8kmVPkbFNIhD4XGnjo3pqqQRQPCzvky/iOlPvR+dYVzV7GQ0q+VENhJpTSxtqdEfx32bNptlwFvdFWGuTd72KX7g5XZMG8X1d1/V0dwSaFp4/NiBzEHWLmRYF3e3nN/+uLcTrN3o2w/EbBcdpuuYnLWTAybluLDUZKc2UHYLGTtFVeiDPvKda39gUgOlDEO9GvTym9Ohf3mf9X1xXQmGDQKxdmKagRck1RirxzXocq4VUHV+DBUpAdRmKxy20+oiGOuxzJutw60IkKKv8k8+iqO8KxUZKmJvmSRTFyfYfTtXLiWBdJhgjvLpiksEZcPAzI4Zvet86AMu/XeA+W8lsmGuRBfJE1m2axRcftdTdHTAv68ikTMUk3CUBPORF2ZU7KtC46aHKQ852hpChSXE65MBD4Plozas4EsJ/tuHQL8QF9I5taoBv/r6AR0pcSESl4mLfZKwZYMCuS3rQ29xlURPMZokTfXHJe1kVAzQqVmdqyU5MEpQOlEmrj9SfD3bUXwxa0GYjV6ePAXZdzyCyOJzEpFQ11liJVJN3WSoS7F0sMhzteLpx2Lpnk=
  on_success: always
  on_failure: always