sudo: required
dist: trusty
language: node_js
node_js:
- node

branches:
  only:
    - master
    - staging

deploy:
  - provider: firebase
    token:
      secure: "Q4lLBMbKEISm6pPurCUNLyzFPorsNLpmOernWFKPR5o4weYRkZCubPiHSboWFUoohzq+lSEwW3o7/6jspmKpcRqCnjOEMID06dYozFc16/mMzTRmL8luzY5FyKiL2ydHUkwYO2S61gyojnk8s/+rOL1M6QqrVsqz7VmbDecioNPyZaNnrPEiKyVjYYaQ4t1F2fGURkEpK7DHnA234WKwFxbRYxmQTDayy3mmSJKcdF16lRGI3xYeP6HtRGGZ6FE7HXyCHgK067owy1rFwc7Q6cMO7G01F8gXaX8CgTAzvOMdnYJg9Bcf/OuaRhES48DWb4MI9Y3K6gA44vkqxmlr/Pw0LiGge7YNDxMTSz+bg+7WmCOSo8/RfNQV0Z+81qKW7Vu4zhhYOcfT0hk3Ba1TUJOHyzQPd+emhWdop4H+1kOmrOHvU9Xc8nQsbXdAcNAS6ESDbrRZeyoXBBWyCEYJ/gpmXto+Ji9NIGoEv8plx24bNA0hn2DdkEqrQv7qPNOqjF7Kbhr7Qc+0eNNeX2qXvGHpdKxlHaXTyQ/qSyuC1GdLLWsx1FQqioiJxRFQP9pNfGRWOD29KEFGFTfh/DGiYeV/ZJvAPXck6T3xmEzfKKSeTX3zWOmHzp3pjctUoa1zN+9is4lXKRRkggpVsFl/j/vgIuPWGn2z0cJUPgYbghE="
    project: "sniphub-prod"
    skip_cleanup: true
    on:
      branch: master
  - provider: firebase
    token:
      secure: "Loe4gGwadYi1sUtVQuiDhJh4Bha7RHBgS48hWflTg1678Abyfbk3dxzZSPUo18H5MlavdLXr/71AntSjmIZJj1yYQrXh6XVskf8pjhjd0JdzLJ+zQTc4FN3sp7oQHusjFUvD/W5tg/wklD22+ELb1pvn1hgaKjNrSg9OyDjk9r+Aejk4+YPwT2bu1J7wohKatmoIsIppuia94z8glySVXaCdY9muTRgshxuCFg/KVRxaFjZYumNvPxhtv4r6BF2YvJliAXOdjVUOq5C1Hu0Jxgv9gh/wzoXohEP25HrHZiznXDlaSb/UB7tYWDwydFjqrYwVDRn1Wf3uc9pHrd9562gVVfnWcyPTyYSHXAm2VWg8t8bAfYVGZhCggkXJzdXOMQO02pb9ArbB22YRQWgEHD+OYW5HMYqSAq7ZKPCdc38a3gQVh4tu/PMEPV9GmfqGRAPCEjWXJxqFiPNHI2GDjAaEmLz74d/EAAfsAR/mwxxe2s/vldpED/2Mal4zgH3IjhJFMY8S7t88LJJkemKOzAoAXeKvePANjnDGlBRx6LmsDVt9k8BTTYIcyJKtT8ltlalVlvD1MNGWrR3d9JoIH7UO4USl2TE6L5JBoteK/yqAPUP6i5YvHOTrRQjbamp75rhumPv0j1YFJaY7HyvtHER98Sw/82DAWjMcaQuWOEA="
    project: "snipz-dev"
    skip_cleanup: true
    on:
      branch: staging

notifications:
  slack:
    rooms:
      secure: nYW3DSi02cfrdBUH5RCArraj6VhtcS8AVktHOaxf4Y8ncebQ53mcrmqkj1wHRE275obDPPiekb/OxIab0BZOtLTocLV01P4kR+PiUsDRgIJJI3YC/LY975wqHcE3Lj6XmqLI6lWEPKhLnkl0Mu3NfdZdW7Bbn05xMICsJzcgpBNiK+PZwvKIrZ6KONFXkyRUI6IJXtMSwT9yUwtZpfr/UFjEBov6wxarmwj3aWwD9jEizn728LRs+ruGzSmsbEuEQZ/cDPU5wbYBpc0GSQQ5u17jkxAP/P43UnOh7CI7H4dwDS99821m4iMekTRR8yhc9kIB5Mq6y1gtjgwFUwVTTe+EsifLqU7y+xRQLI2xn1S1WWtxmKcAD5ZJxShmXcrMTofa9BswR9sfEl9RumSBPYWeEv+g1Knipx9AlJYg1CXi3t3vZFV5gbcTI3omj0eKRCoqtr9fFV1roLmy6BfIcVCklx7YH8+w2KZWgdz2ECWc6/qFcye45S+nDmWzYV/dMp7gx5gtVOCdViKyrWHDhf4+OV49He+DCXbVKWSN6BpNM9Q1ZHy5gRKMKh9kX9QcaDZXhJsCwLEtJb09hpomkfn1mJia8UIO6i/qPxOIpNIKsb7IlYpq1N2JP60C3sLT4l4lUOxg5vMhXywJEMcAGi3lajCv1UlkDnCKwYdedY8=
    on_success: change
    on_failure: change

addons:

apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli karma
- npm install
- ng build --prod

# script: karma start karma.conf.js --single-run

env:
  global:
    secure: Q4lLBMbKEISm6pPurCUNLyzFPorsNLpmOernWFKPR5o4weYRkZCubPiHSboWFUoohzq+lSEwW3o7/6jspmKpcRqCnjOEMID06dYozFc16/mMzTRmL8luzY5FyKiL2ydHUkwYO2S61gyojnk8s/+rOL1M6QqrVsqz7VmbDecioNPyZaNnrPEiKyVjYYaQ4t1F2fGURkEpK7DHnA234WKwFxbRYxmQTDayy3mmSJKcdF16lRGI3xYeP6HtRGGZ6FE7HXyCHgK067owy1rFwc7Q6cMO7G01F8gXaX8CgTAzvOMdnYJg9Bcf/OuaRhES48DWb4MI9Y3K6gA44vkqxmlr/Pw0LiGge7YNDxMTSz+bg+7WmCOSo8/RfNQV0Z+81qKW7Vu4zhhYOcfT0hk3Ba1TUJOHyzQPd+emhWdop4H+1kOmrOHvU9Xc8nQsbXdAcNAS6ESDbrRZeyoXBBWyCEYJ/gpmXto+Ji9NIGoEv8plx24bNA0hn2DdkEqrQv7qPNOqjF7Kbhr7Qc+0eNNeX2qXvGHpdKxlHaXTyQ/qSyuC1GdLLWsx1FQqioiJxRFQP9pNfGRWOD29KEFGFTfh/DGiYeV/ZJvAPXck6T3xmEzfKKSeTX3zWOmHzp3pjctUoa1zN+9is4lXKRRkggpVsFl/j/vgIuPWGn2z0cJUPgYbghE=
