sudo: required
dist: trusty
language: node_js
node_js:
- node

branches:
  only:
    - master
    - staging

deploy:
  - provider: firebase
    token:
      secure: "Q4lLBMbKEISm6pPurCUNLyzFPorsNLpmOernWFKPR5o4weYRkZCubPiHSboWFUoohzq+lSEwW3o7/6jspmKpcRqCnjOEMID06dYozFc16/mMzTRmL8luzY5FyKiL2ydHUkwYO2S61gyojnk8s/+rOL1M6QqrVsqz7VmbDecioNPyZaNnrPEiKyVjYYaQ4t1F2fGURkEpK7DHnA234WKwFxbRYxmQTDayy3mmSJKcdF16lRGI3xYeP6HtRGGZ6FE7HXyCHgK067owy1rFwc7Q6cMO7G01F8gXaX8CgTAzvOMdnYJg9Bcf/OuaRhES48DWb4MI9Y3K6gA44vkqxmlr/Pw0LiGge7YNDxMTSz+bg+7WmCOSo8/RfNQV0Z+81qKW7Vu4zhhYOcfT0hk3Ba1TUJOHyzQPd+emhWdop4H+1kOmrOHvU9Xc8nQsbXdAcNAS6ESDbrRZeyoXBBWyCEYJ/gpmXto+Ji9NIGoEv8plx24bNA0hn2DdkEqrQv7qPNOqjF7Kbhr7Qc+0eNNeX2qXvGHpdKxlHaXTyQ/qSyuC1GdLLWsx1FQqioiJxRFQP9pNfGRWOD29KEFGFTfh/DGiYeV/ZJvAPXck6T3xmEzfKKSeTX3zWOmHzp3pjctUoa1zN+9is4lXKRRkggpVsFl/j/vgIuPWGn2z0cJUPgYbghE="
    project: "sniphub-prod"
    skip_cleanup: true
    on:
      branch: master
  - provider: firebase
    token:
      secure: "FDDcIim5pFhxlUth2pMNwrd7eRPUxs/D/prhLNpblPGDIUMHuQgObjtwcBcbtJXo86L9PWIvJieGMKvVgDSFerhxPVBTcm/ZJ5tiPPiV4UB+Bwyu8xBzV5ikxsecG7Mb6Gg03ql3lXG/RMjM78eZbLyUcQGg2PYYV1gWucrcijF/M/YKCaEhNMT4/ZcYrZYSdBTBO59TdgWNjM4rXuN34eObQp8ta+oUC4cLHmvibO5JvunZHdKW25m9V7ai9AJN0OcyVOYql3ZTMSWl26MRDDNEzvVtBk4jEWlPYKw7qKv0NsDok9n6Qnx8PGOad9OTIyJAQFC6wBWNleeX3fXRf0rALKUhZHVS7LMzX/goyi+dFORRiWNiwHIOWpWL7QkZJ1WUwt2/HLuc+6OhFv7D1eN3uTnu52GIKvyRgLK6FLNWMw1HzckfZUDY/p89MMO37os0zEr+s/tndmEXR8gEOsR/WIGpFtfOw2aw4yiFI1KG4XGqQbEnmG07aGZPiKl2WupvBQ1XCOSzivr0n1BUsGmXa7QJsM0bcqtWrsKKgM7vVDKBx1r0/p4dk9yNoKld/NubERdvMI7M2qAG4sUSsKKT8Rvqw/hj83VIuwBYIDm75DJxwXYEcD4/OUgTqitHS9Ck+91vIpgzAF7NUy82EF2YskWDxUAcIhkUtqp19fo="
    project: "sniphub-staging"
    skip_cleanup: true
    on:
      branch: staging

notifications:
  slack:
    rooms:
      secure: nYW3DSi02cfrdBUH5RCArraj6VhtcS8AVktHOaxf4Y8ncebQ53mcrmqkj1wHRE275obDPPiekb/OxIab0BZOtLTocLV01P4kR+PiUsDRgIJJI3YC/LY975wqHcE3Lj6XmqLI6lWEPKhLnkl0Mu3NfdZdW7Bbn05xMICsJzcgpBNiK+PZwvKIrZ6KONFXkyRUI6IJXtMSwT9yUwtZpfr/UFjEBov6wxarmwj3aWwD9jEizn728LRs+ruGzSmsbEuEQZ/cDPU5wbYBpc0GSQQ5u17jkxAP/P43UnOh7CI7H4dwDS99821m4iMekTRR8yhc9kIB5Mq6y1gtjgwFUwVTTe+EsifLqU7y+xRQLI2xn1S1WWtxmKcAD5ZJxShmXcrMTofa9BswR9sfEl9RumSBPYWeEv+g1Knipx9AlJYg1CXi3t3vZFV5gbcTI3omj0eKRCoqtr9fFV1roLmy6BfIcVCklx7YH8+w2KZWgdz2ECWc6/qFcye45S+nDmWzYV/dMp7gx5gtVOCdViKyrWHDhf4+OV49He+DCXbVKWSN6BpNM9Q1ZHy5gRKMKh9kX9QcaDZXhJsCwLEtJb09hpomkfn1mJia8UIO6i/qPxOIpNIKsb7IlYpq1N2JP60C3sLT4l4lUOxg5vMhXywJEMcAGi3lajCv1UlkDnCKwYdedY8=
    on_success: change
    on_failure: change

addons:

apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli karma
- npm install
- make build

# script: karma start karma.conf.js --single-run

env:
  global:
    secure: Q4lLBMbKEISm6pPurCUNLyzFPorsNLpmOernWFKPR5o4weYRkZCubPiHSboWFUoohzq+lSEwW3o7/6jspmKpcRqCnjOEMID06dYozFc16/mMzTRmL8luzY5FyKiL2ydHUkwYO2S61gyojnk8s/+rOL1M6QqrVsqz7VmbDecioNPyZaNnrPEiKyVjYYaQ4t1F2fGURkEpK7DHnA234WKwFxbRYxmQTDayy3mmSJKcdF16lRGI3xYeP6HtRGGZ6FE7HXyCHgK067owy1rFwc7Q6cMO7G01F8gXaX8CgTAzvOMdnYJg9Bcf/OuaRhES48DWb4MI9Y3K6gA44vkqxmlr/Pw0LiGge7YNDxMTSz+bg+7WmCOSo8/RfNQV0Z+81qKW7Vu4zhhYOcfT0hk3Ba1TUJOHyzQPd+emhWdop4H+1kOmrOHvU9Xc8nQsbXdAcNAS6ESDbrRZeyoXBBWyCEYJ/gpmXto+Ji9NIGoEv8plx24bNA0hn2DdkEqrQv7qPNOqjF7Kbhr7Qc+0eNNeX2qXvGHpdKxlHaXTyQ/qSyuC1GdLLWsx1FQqioiJxRFQP9pNfGRWOD29KEFGFTfh/DGiYeV/ZJvAPXck6T3xmEzfKKSeTX3zWOmHzp3pjctUoa1zN+9is4lXKRRkggpVsFl/j/vgIuPWGn2z0cJUPgYbghE=
